name = "test_Stroke_R01"
version = "0.1.2"
repository_url = "https://github.com/mtillman14/test-Stroke-R01"
language = "matlab"
authors = [
    { name = "Mitchell Tillman", email = "mtillman14@gmail.com" },
]
dependencies = [
    "load_gaitrite==v0.1.3",
    "load_xsens",
    "load_delsys",
]
readme = "README.md"
