# ROSS project configuration file
name = "test-Stroke-R01"
version = "0.1.0"
repository_url = "https://github.com/mtillman14/test-Stroke-R01"
language = "matlab"
authors = [

]
dependencies = [
    "load_gaitrite",
    "load_xsens",
    "load_delsys"
]
readme = "README.md"
