[subjects]
run = [
    #"SS01",
    #"SS02",
    #"SS03",
    #"SS04",
    #"SS05",
    #"SS06",
    #"SS08",
    #"SS09",
    #"SS10",
    #"SS13",
    #"SS18",
    #"SS20",
    #"SS21",
    #"SS23",
    #"SS24",
    #"SS27"
]

plot = [
    # "SS01",
    # "SS02",
    # "SS03",
    # "SS04",
    # "SS05",
    # "SS06",
    # "SS08",
    # "SS09",
    # "SS10",
    # "SS13",
    # "SS18",
    # "SS20",
    # "SS21",
    # "SS23",
    # "SS24",
    # "SS27"
]